# Generated by Django 3.2.9 on 2021-11-30 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('company_type', models.CharField(blank=True, max_length=100)),
                ('total_categories', models.IntegerField(blank=True, null=True)),
                ('total_deals', models.IntegerField(blank=True, default=1, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_title', models.CharField(blank=True, max_length=100, null=True)),
                ('deal_price', models.FloatField(default=0)),
                ('validity_from', models.DateTimeField(blank=True, null=True)),
                ('validity_till', models.DateTimeField(blank=True, null=True)),
                ('deal_description', models.CharField(blank=True, max_length=500, null=True)),
                ('deal_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
